### ISSUE TITLE
Document the error correction algorithm

### ISSUE THREAD

**Issue by dev-zzo** [TLeconte/acarsdec#24]
Hello Thierry,

First let me thank you for this great piece of software. It does an amazing job indeed.

I would like to request you to please document the exact algorithm you have implemented to correct errors. I have figured out most of it but the syndrome part still throws me off as I am not super good with CRC maths.

My final goal is to improve the algorithm to ensure the corrected messages are well formed e.g. the aircraft reg. number doesn't contain oddball characters. Ideally I'd appreciate a callback function inserted into the error correction code which I could then modify. I'd also need to ensure the algorithm actually completes. :-)

**Comment by sv1** [comment]
Hello Thierry,

I do not know if it has anything to do with what dev-zzo says, but since the commits on Jan 11, I can not decode any message, anymore.  All I get is too many parity errors.

**Comment by dev-zzo** [comment]
@sv1 It is not related; I were asking for something that was actually working. :-) Please create a new issue and if possible try to spot the exact offending commit.

**Comment by TLeconte** [comment]
Yes open a new issue.
I just recheck now with my  airspy and it seems  working ....
Hope I have not break rtl as I don't have one any more now.
Could someone else confirm that it works (or not)  with rtl  ?

**Comment by TLeconte** [comment]
@sv1 I just fixed a nasty cast problem introduced by commit [edd0bd70b1bac1d](https://github.com/TLeconte/acarsdec/commit/058eb01964d655ad32f33ff83edd0bd70b1bac1d)
It was working on ARM but not on x86_64  :-(
Could you try last version ?

**Comment by sv1** [comment]
On Thu, 2018-01-25 at 00:38 -0800, Thierry Leconte wrote:
> @sv1 I just fixed a nasty cast problem introduced by commit
> edd0bd70b1bac1d
> It was working on ARM but not on x86_64 :-(
> Could you try last version ?

I am on a trip now Thierry, as soon as I get back I will do.

thank you very much.

**Comment by sv1** [comment]
Sorry for the delay!!!

Everything is working great

Thanks Thierry

**Comment by rfrht** [comment]
@TLeconte bug keeping: You may now close this bug report! ;-)

**Comment by TLeconte** [comment]
ok
