### ISSUE TITLE
index() is deprecated POSIX function

### ISSUE THREAD

**Issue by hhrhhr** [TLeconte/acarsdec#27]
https://github.com/TLeconte/acarsdec/blob/d11c58643ce4815fedad7f243de8b225a5ad7f00/label.c#L150-L156

from [Open Group Base Specifications Issue 6](http://pubs.opengroup.org/onlinepubs/009695399/functions/index.html):

_The index() function shall be equivalent to strchr()... The strchr() function is preferred over this function.
For maximum portability, it is recommended to replace the function call to index() as follows:_
````#define index(a,b) strchr((a),(b))````

**Comment by TLeconte** [comment]
fixed
