### ISSUE TITLE
bzero() is deprecated POSIX function

### ISSUE THREAD

**Issue by hhrhhr** [TLeconte/acarsdec#28]
https://github.com/TLeconte/acarsdec/blob/d11c58643ce4815fedad7f243de8b225a5ad7f00/acarsserv.c#L289

from [Open Group Base Specifications Issue 6](http://pubs.opengroup.org/onlinepubs/009695399/functions/bzero.html):

_The memset() function is preferred over this function.
For maximum portability, it is recommended to replace the function call to bzero() as follows:_
````#define bzero(b,len) (memset((b), '\0', (len)), (void) 0)````

**Comment by TLeconte** [comment]
fixed
