### ISSUE TITLE
Discussion about compile/run-time sample rate selection

### ISSUE THREAD

**Issue by ckuethe** [TLeconte/acarsdec#30]
Moving the discussion here from https://github.com/TLeconte/acarsdec/commit/058eb01964d655ad32f33ff83edd0bd70b1bac1d#diff-3bf2ef42cf6b8f3ece930bed9bcb1f99

As an experiment, I increased my RTLMULT to 204 so I could get 2.56Ms/s and will see if this has an effect on my reception quality. I'm only using 30% of 1 core on a Pi3.

**Comment by dev-zzo** [comment]
My RPi Zero nodes have ~50% CPU utilization when listening on three channels, so certainly not a big issue there as well.

**Comment by TLeconte** [comment]
I will still use 2.0M./s as default. Some others rtl_sdr software limit sample rate to 2.4M/s 
I updated the README to make things more clear
