### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by gcopter1** [TLeconte/acarsdec#38]
I notice that, after a while, the program stops working. I’m using VNC viewer mainly, to connect to the RPi, but this also happens with PuTTy. 
On VNC, after the program stops working, I can relaunch it, I don’t even have to log in to the RPi, it just starts running right away. 

Program stops working after long unattended period, meaning, I’m not hovering my cursor over the open terminal window or interacting with it.

**Comment by TLeconte** [comment]
no error messages ?

**Comment by gcopter1** [comment]
No error messages. Over 7 hours.
