### ISSUE TITLE
Export ACARS data to dump1090 / BEAST format?

### ISSUE THREAD

**Issue by Romeo-Golf** [TLeconte/acarsdec#4]
While the ACARS messages may not all continue possition information, would it be possible to export at least those that do into dump1090 via the BEAST binary format?

**Comment by TLeconte** [comment]
It means to know the acars message format for position.
Alas, there is no such format, each airway company use its own.
I know some of them by observation, but there is so much different formats ....
I think that the best is to store acars in a database (via acarsserv or others) and then do post processing.
format conversion is not acarsdec job
