### ISSUE TITLE
README errors

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/acarsdec#47]
Hi Thierry, 
As the make process creates device specific executables depending on the -f parameter, all references to just 'acarsdec' as the program name are incorrect.
See: 
https://github.com/TLeconte/acarsdec#usage
https://github.com/TLeconte/acarsdec#examples

Also under 
https://github.com/TLeconte/acarsdec#compilation
The 'make -f Makefile.sdrplay' is missing.
And maybe you could mention here that the name of the executable that is created also depends on the device..

Cheers,
Dick

**Comment by TLeconte** [comment]
hum , I accepted a pull request about sdrplay (I don't own one), but I did not see that it touch, without any reason, the others Makefile.
I did not like the fact that the executable have different name, even if I could understand that it's useful for someone that use different dongles.
So I will change the Makefiles and, yes, and add to the README for sdrplay could be useful. I will se that latter
