### ISSUE TITLE
rtl_tcp support?

### ISSUE THREAD

**Issue by limaunion** [TLeconte/acarsdec#48]
Hi. This might be a feature request if currently is not supported.

I'm using a remote RPI3 and I'd like to be able to receive the input from rtl_tcp or from GQRX UDP raw audio stream. Can acarsdec receive the input from rtl_tcp of from GQRX ?

Thanks in advance!

**Comment by jmceara** [comment]
+1 for this! Would be very usefull for multiple-decodings. For example: if you run rtl_tcp, you can connect acarsdec and vdlm2dec using same dongle (if you use same frequency inside ~2mhz/bandwidth).

**Comment by dterweij** [comment]
Not realy. Only one client can connnect to the rtl_tcp server.

**Comment by jmceara** [comment]
nop, you can use this tool for this: https://github.com/simonyiszk/rtl_mus

Em seg, 25 de mar de 2019 23:40, Danny Terweij <notifications@github.com>
escreveu:
