### ISSUE TITLE
-D parameter and it's position in the parameter list

### ISSUE THREAD

**Issue by DickvanNoort** [TLeconte/acarsdec#56]
Placing the -D parameter between the -r parameter and the frequency list causes a warning.
Moving it to just before the -r parameter sloves this.
Not sure how 'specific' the position of this -D parameter (or others) is.
See these two examples:

$/usr/local/bin/acarsdec -l "/home/pi/acarsdec/logs/$(date +"%Y%m%d")-5.log" -n 10.0.0.2:9742 -p 70 -r 00000005 -D 131.525 131.725 131.825
Found Rafael Micro R820T tuner
WARNING: Invalid frequency 0
Exact sample rate is: 2000000.052982 Hz

$/usr/local/bin/acarsdec -l "/home/pi/acarsdec/logs/$(date +"%Y%m%d")-5.log" -n 10.0.0.2:9742 -p 70 -D -r 00000005  131.525 131.725 131.825
Found Rafael Micro R820T tuner
Exact sample rate is: 2000000.052982 Hz

But maybe the example in the README is the required sequence of parameters.
acarsdec [-v] [-o lv] [-t time] [-A] [-n|N|j ipaddr:port] [-i stationid] [-l logfile [-H|-D]] -r rtldevicenumber f1 [f2] [... fN] | -s f1 [f2] [... fN]

Cheers,
Dick

**Comment by TLeconte** [comment]
As stated in the help, -r and frequencies must be last.
Not really pretty, but ...
