### ISSUE TITLE
too many Parity Errors

### ISSUE THREAD

**Issue by xantegh** [TLeconte/acarsdec#61]
Thank you for keeping this hobby active Thierry.

please find below a quick feedback from Washington.

pi@raspberrypi:~/acars-dec $ acarsdec -v -o4 -r 0 130.825 131.125 131.425 131.550 131.725
Found 1 device(s):
  0:  Realtek, RTL2838UHIDIR, SN: 00000001

Using device 0: Generic RTL2832U OEM
Found Rafael Micro R820T tuner
Tuner gain : 49.600000
Set center freq. to 131750000Hz
Exact sample rate is: 2000000.052982 Hz
Decoding 5 channels
{"timestamp":1555400604.623349,"station_id":"raspberr","channel":3,"freq":131.550,"level":-12,"error":0,"mode":"2","label":"4T","block_id":"2","ack":"G","tail":"C-FDST","flight":"AC0979","msgno":"M76A","text":"AGFSR AC0979/15/16/SJDYVR/0743Z/207/4713.9N12200.6W/360/      /0033/0112/M51/305031/0465/   /---/0401/0412/----/----"}
{"timestamp":1555400611.095185,"station_id":"raspberr","channel":3,"freq":131.550,"level":-12,"error":0,"mode":"2","label":"_d","block_id":"3","ack":"H","tail":"C-FDST","flight":"AC0979","msgno":"S65A"}
{"timestamp":1555400712.5158141,"station_id":"raspberr","channel":4,"freq":131.725,"level":-18,"error":0,"mode":"2","label":"12","block_id":"4","ack":false,"tail":"C-FONK","flight":"WO0118","msgno":"M66A","text":"N 49.131,W120.428,29755,074510, 232,.C-FONK,1114"}
#1 too many parity errors
#5 too many parity errors
{"timestamp":1555400842.02856,"station_id":"raspberr","channel":3,"freq":131.550,"level":-6,"error":0,"mode":"2","label":"Q0","block_id":"6","ack":false,"tail":"C-FDST","flight":"AC0979","msgno":"S67A"}
{"timestamp":1555400849.729044,"station_id":"raspberr","channel":3,"freq":131.550,"level":-10,"error":0,"mode":"2","label":"4s","block_id":"7","ack":false,"tail":"C-FDST","flight":"AC0979","msgno":"M79A","text":"DFR AC0979/15"}
{"timestamp":1555400855.873071,"station_id":"raspberr","channel":3,"freq":131.550,"level":-13,"error":0,"mode":"2","label":"_d","block_id":"8","ack":"L","tail":"C-FDST","flight":"AC0979","msgno":"S68A"}
{"timestamp":1555400861.11618,"station_id":"raspberr","channel":3,"freq":131.550,"level":-13,"error":0,"mode":"2","label":"_d","block_id":"9","ack":"M","tail":"C-FDST","flight":"AC0979","msgno":"S69A"}
{"timestamp":1555400904.2060759,"station_id":"raspberr","channel":3,"freq":131.550,"level":-11,"error":0,"mode":"2","label":"Q0","block_id":"2","ack":false,"tail":"C-FDST","flight":"AC0979","msgno":"S72A"}
#5 miss txt end
#5 parity error(s): 2
#5 crc error
#5 errors fixed
{"timestamp":1555400918.3817041,"station_id":"raspberr","channel":4,"freq":131.725,"level":-21,"error":2,"mode":"2","label":"_d","block_id":"0","ack":"B","tail":"N640VA","flight":"VX1010","msgno":"S18A"}
{"timestamp":1555400930.17842,"station_id":"raspberr","channel":4,"freq":131.725,"level":-18,"error":0,"mode":"2","label":"_d","block_id":"3","ack":"E","tail":"N640VA","flight":"VX1010","msgno":"S21A"}
#5 miss txt end
#5 parity error(s): 3
#5 crc error
#5 errors fixed
{"timestamp":1555400941.649678,"station_id":"raspberr","channel":4,"freq":131.725,"level":-22,"error":3,"mode":"2","label":"_d","block_id":"6","ack":"H","tail":"N640VA","flight":"VX=\u00165:","msgno":"S24P"}
#5 too many parity errors
#5 parity error(s): 3
#5 crc error
#5 not able to fix errors
#5 too many parity errors

**Comment by TLeconte** [comment]
It's normal in verbose mode (-v) .
There is no real good way to be sure that there is a packet to decode, so acarsdec try and the crc check tell if iit was a real acars packet or just noise.
