### ISSUE TITLE
Compile Options making Problems on Raspbian

### ISSUE THREAD

**Issue by Roethenbach** [TLeconte/acarsdec#78]
On my Raspberry (Raspberry Pi OS buster both armhf and arm64) acarsdec was not able to receive messages. No error was shown. Now I found the problem: the compile options. 
`add_compile_options(-O2)` does not work! It works after changing to `add_compile_options(-Ofast -march=native )`.

**Comment by TLeconte** [comment]
Ok 
Strange, in general it's more the -Ofast that is not supported.
But I commited your fix as more and more distro support a gcc with -Ofast
