### ISSUE TITLE
acarsdec make

### ISSUE THREAD

**Issue by alibenari** [TLeconte/acarsdec#79]
I am getting the error listed below on the final entry and I would appreciate if someone can point me in the right direction. BTW I am only copy add paste able in programming.
Thank you

pi@acars:~/acars $ cd acarsdec
pi@acars:~/acars/acarsdec $ make -f Makefile.rtl
make: Makefile.rtl: No such file or directory
make: *** No rule to make target 'Makefile.rtl'.  Stop.

**Comment by TLeconte** [comment]
acarsdec don't use Makefile.rtl anymore.
See te README for more info
