### ISSUE TITLE
Using 2 instances of acarsdec on rpi

### ISSUE THREAD

**Issue by keukenrol** [TLeconte/acarsdec#81]
Hi

I am interested in using 2 instances of acarsdec with two different rtl dongles. Reason being that the dongles have a bandwidth of 2.4MHz which is too narrow to cover both 131 and 136MHz acars channels.
What should be the best method? Call the program twice with different parameters and run in background?

Second question: Is it possible to have a web preview?

Third question: Can the logs be written realtime to a csv? I would love to show them on my custom webpage and possibly link them to the basestation.sqb from VRS like they did with acarsdeco2.

Kind regards

**Comment by TLeconte** [comment]
- I never try that, but yes you must be able to run 2 acarsdec instances with different rtl device number (ie : -r 0 and -r 1 )
 But where will you send the results ? 
- What do you mean by a web preview ? An integrated web server ?
- You want that I add a csv format to -o option ?

**Comment by TLeconte** [comment]
I will not code an integrated web server, not my domain.
Don't json a good format for the log ? Because it already exist : -o 4 
I don't think csv is a good format for acars because there are \n in message acars body
There is already the -l option to tell where acarsdec save its log

**Comment by keukenrol** [comment]
Allright, fairly new to it all. I'll use the json. Thanks!
